# Generated by Django 5.2.1 on 2025-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_blogpost_profile_service_delete_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(default=1, upload_to='developers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='cv_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('CLIENT', 'Client'), ('VISITOR', 'Visitor')], default='VISITOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text="Font Awesome class, e.g., 'fas fa-laptop-code'", max_length=50),
        ),
    ]
