# Generated by Django 5.2.1 on 2025-10-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_blogpost_author_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text="Optional: Link to the partner's website.", null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which the logo appears (lower numbers first).')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
