# Generated by Django 5.2.1 on 2025-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='client_logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are displayed first')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.AlterField(
            model_name='developer',
            name='cv_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
