# Generated by Django 5.2.1 on 2025-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0006_client_delete_partner_alter_developer_cv_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Innovative Software Solutions for Your Business', max_length=200)),
                ('subtitle', models.TextField(default='We build robust, scalable, and elegant web applications.')),
                ('background_image', models.ImageField(help_text='Recommended size: 1920x1080 pixels', upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one hero section can be active at a time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
