# Generated by Django 5.2.1 on 2025-10-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0007_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
